### ISSUE TITLE
Charger, Circuit or Installation (500 internal server error)

### ISSUE THREAD

**Issue by c0mplex1** [custom-components/zaptec#109]
When the Zaptec EV Charger integration receives a "Charger, Circuit or Installation (500 internal server error)" error, the Zaptec Load Balancing blueprint script usually generates an error as well.
This error can be avoided by adding a condition between the variables and the service, preventing the script from executing.
`- condition: "{{ is_state(binary_sensor_installation, 'on') }}"`
Perhaps a similar solution could be added to charger integration?

**Comment by c0mplex1** [comment]
Let me try to explain:

When Zaptec cloud does not respond or returns an error, see discussion #90: 
then often the [Zaptec Load Balancing](https://github.com/svenakela/ha/tree/main/zaptec#zaptec-load-balancing) Blueprint automation will also place errors and warnings in the log.

The value of the 4 variables ​​used in the blueprint automation are obtained from the Zaptec EV Charger integration via
`{{ integration_entities('zaptec') ... }}` are not valid at that time.
The Load Balancing automation will therefore not work (properly).

This can be prevented by adding an extra condition into the blueprint automation, so that the automation cannot be run if unknown values ​​are received.

```
action:
  - variables:
      _main_current_l1: !input input_main_current_l1
      ......
      my_device_id: "{{ integration_entities('zaptec') | first | device_id }}"
      number_avail_curr: "{{ integration_entities('zaptec') | select('match', 'number.*_available_current') | first }}"
      sensor_charger_mode: "{{ integration_entities('zaptec') | select('match', 'sensor.*_charger_mode') | first }}"
      binary_sensor_installation: "{{ integration_entities('zaptec') | select('match', 'binary_sensor.*_installation') | first }}"

  - condition: "{{ is_state(binary_sensor_installation, 'on') }}"

  - service: zaptec.limit_current
    data:
      ......

```

I am not a (Python) programmer, but perhaps a similar solution can also be built (somewhere) into your Zaptec EV Charger integration, so that you no longer get errors when the Zaptec cloud does not respond for a while.
