### ISSUE TITLE
Setup fails in 2023.6 - Requirements not found: ['azure-servicebus==7.0.1'].

### ISSUE THREAD

**Issue by onkelfarmor** [custom-components/zaptec#34]
Setup fails in 2023.6 beta:

Setup failed for custom integration zaptec: Requirements for zaptec not found: ['azure-servicebus==7.0.1'].

**Comment by Hellowlol** [comment]
Yeah, hopefully they will get it solved. If not i can remove this requirement. Atm this integration supports both push and pull.

**Comment by onkelfarmor** [comment]
Can I do something so it works in the meantime?

**Comment by Hellowlol** [comment]
You can install the latest pre release from hacs and see if it’s working

**Comment by onkelfarmor** [comment]
Tried, doesn’t.

**Comment by Hellowlol** [comment]
Please post the error

**Comment by onkelfarmor** [comment]
I did that in the first post.

**Comment by Hellowlol** [comment]
Ah, i see. I forgot to remove the requirement. I have created a new release. Please check it it works

**Comment by onkelfarmor** [comment]
Now it works, thanks!

**Comment by magne74** [comment]
Mulig dette løser mitt problem også. Hvordan installere en beta?

**Comment by magne74** [comment]
Fant ut av det og det løste mitt problem også.

**Comment by TorbjornMohn** [comment]
> Fant ut av det og det løste mitt problem også.

Hvordan gjorde du det. Jeg finner ikke ut av det😢

**Comment by magne74** [comment]
Gå inn i zaptec-integrasjonen i hacs. Velg last ned på nytt via de tre prikkene øverst i høyre hjørne. Tillat beta-versjoner. Så måtte jeg først velge 0.0.3 fra 0.0.5. Så fikk jeg lov til å velge den siste beta-versjonen...

**Comment by TorbjornMohn** [comment]
> Gå inn i zaptec-integrasjonen i hacs. Velg last ned på nytt via de tre prikkene øverst i høyre hjørne. Tillat beta-versjoner. Så måtte jeg først velge 0.0.3 fra 0.0.5. Så fikk jeg lov til å velge den siste beta-versjonen...

TAKK!!!! :-)

**Comment by Olen** [comment]
Bekrefter at siste beta fungerer her også.

**Comment by philsson** [comment]
Just created a fork to fix this. Should not HACS propose an update if one is lagging behind?

**Comment by Olen** [comment]
No need to create a fork.
Just install the latest beta from hacs.

**Comment by gertlind** [comment]
Beta works perfectly, thanks for this.

**Comment by juicydut** [comment]
when you say it works, does it mean you can see sensors/states of the charger? or it also means you are able to call the services (start, stop charging). When I tried to call start/stop charging service, it gives an error "required key not provided @ data['charger_id']" any suggestions? thx

**Comment by philsson** [comment]
> when you say it works, does it mean you can see sensors/states of the charger? or it also means you are able to call the services (start, stop charging). When I tried to call start/stop charging service, it gives an error "required key not provided @ data['charger_id']" any suggestions? thx

I tried this just yesterday and it works. I have only had my charger for a couple of weeks and not played around with it too much yet but I've noticed that for me the charger needs to be "charging" before I can do anything from the zaptec service. I can then pause and resume, but if I have the charger in "smart mode" through Tibber then before it starts charging I cannot control it. So as far as I can tell the charger needs to be configured to always charge and then if you do not want to charge immediatly you'd have to pause it just after connecting the car. I would love to hear more from others on this but this "issue" may be the wrong forum for that. Anyways, here is some code I have in Lovelance

```yaml
type: horizontal-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    icon: mdi:pause
    name: Stop Pause Charging
    tap_action:
      action: call-service
      service: zaptec.stop_pause_charging
      target: {}
      data:
        charger_id: bxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  - show_name: true
    show_icon: true
    type: button
    icon: mdi:play-pause
    name: Resume Charging
    tap_action:
      action: call-service
      service: zaptec.resume_charging
      data:
        charger_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
