### ISSUE TITLE
Automation on 'sensor.<alias>_charger_mode'

### ISSUE THREAD

**Issue by MichaelOE** [custom-components/zaptec#94]
Hi
First, thank you very much for this integration 👍
Sorry, if this is the wrong place for asking this question.
I am looking for a way to get a notification whenever my car is unplugged from the charger.
I know I can monitor the current or something similar, but it's it possible to do an automation on the _charger_mode entity?

**Comment by philsson** [comment]
I can share my automation for notifications. Tells you all the possible states like connected, disconnected, waiting, charging etc.
```yaml
alias: Zaptec Notifications
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.zaptec_go_charger_mode
condition: []
action:
  - service: notify.notify
    data:
      message: "{{ trigger.to_state.state }}"
      title: Zaptec
      data:
        tag: zaptec_state
mode: single
```
